// components/footer.tsx
import { navigation } from "config";
import { Box, Link } from "components";

const nav = navigation.footerNav;

export default function Footer() {
  return (
    <Box fullSize as="footer" className="mx-0">
      <hr className="mt-12 border-dark" />
      <Box
        as="div"
        className="flex flex-col py-6 sm:px-6 md:flex-row md:items-center md:justify-between"
      >
        {nav.length && (
          <div className="flex justify-center space-x-6 md:order-2">
            {nav.map((item) => (
              <Link
                key={item.title}
                href={item.href}
                animatedUnderline
                className="font-medium text-dark"
              >
                {item.title}
              </Link>
            ))}
          </div>
        )}
        <div className="mt-8 flex flex-col items-center justify-center font-medium md:order-1 md:mt-0 md:flex-row md:flex-nowrap md:justify-start">
          <p className="ml-0 mt-4 md:mt-0 md:ml-2">&copy; 2023 &mdash; </p>
          &nbsp;
          <p>Design and development by </p>&nbsp;
          <Link
            href="https://github.com/crstnmac"
            className="font-extrabold text-transparent text-2xl bg-clip-text bg-gradient-to-r from-yellow-300 via-purple-400 to-green-300"
          >
            crstnmac
          </Link>
        </div>
      </Box>
    </Box>
  );
}

// components/Page/Footer.vue
<script lang="ts" setup>
import p from './../../package.json'
import { IApp } from '~/utils/app'
const app = useState<IApp>('app')
</script>

<template>
  <footer>
    <section
      class="max-w-8xl mx-auto px-4 lg:px-8 flex-1 flex w-full space-x-20"
    >
      <div class="w-full py-4 text-center">
        <div class="text-xs text-gray-600 dark:text-gray-400">
          Copyright © 2022 <a :href="app.author.link">{{ app.author.name }}</a
          >. All rights reserved. Made with <span class="text-red-500">❤</span>
          <div class="flex flex-col space-x-2 items-center">
            <span class="text-center md:text-right">
              designed by
              <a
                href="https://github.com/crstnmac"
                class="font-extrabold text-transparent text-2xl bg-clip-text bg-gradient-to-r from-yellow-300 via-purple-400 to-green-300"
                >crstnmac</a
              >
            </span>
            <span
              class="block bg-blue-500 rounded px-1 py-0.5 text-white text-xs"
            >
              {{ p.devDependencies.nuxt }}
            </span>
          </div>
        </div>
      </div>
    </section>
  </footer>
</template>
