// components/AboutMe.vue
<template>
  <div class="flex flex-col justify-center items-start mx-auto pb-8 mt-8">
    <div class="flex flex-col-reverse w-full sm:flex-row items-center">
      <div class="flex flex-col pr-8 ml-6">
        <div
          class="text-4xl font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-yellow-400 via-purple-500 to-green-400 dark:from-yellow-300 dark:via-purple-400 dark:to-green-300"
        >
          Criston Mascarenhas
        </div>
        <div class="text-sm pl-1">
          Frontend Developer at
          <Anchor
            href="https://timeless.co"
            target="_blank"
            class="font-bold hover:no-underline hover:text-slate-900 hover:dark:text-white capitalize"
            >Timeless.co
          </Anchor>
        </div>
        <div class="text-md mt-4 font-semibold italic text-gray-400">
          "Make it work, make it right, make it fast." - Kent Beck
        </div>
        <div class="mt-4">
          <Anchor
            href="https://discord.com/users/484623360899284992"
            target="_blank"
          >
            <img
              src="https://lanyard.cnrad.dev/api/484623360899284992"
              alt="discord"
              width="auto"
              height="auto"
              class="inline-block w-full rounded-xl"
            />
          </Anchor>
        </div>
      </div>
      <div class="mb-8 md:ml-auto w-45">
        <img
          src="https://avatars.githubusercontent.com/u/20360870?v=4"
          class="inline-block w-full rounded-full"
          alt="crstnmac"
          width="100"
          height="100"
        />
      </div>
    </div>
  </div>
</template>
<script setup lang="ts"></script>

// components/about-me.tsx
import { Link, Picture } from "components";

export default function AboutMe() {
  return (
    <div className="flex flex-col justify-center items-start mx-auto mt-8">
      <div className="flex flex-col-reverse w-full sm:flex-row items-center">
        <div className="flex flex-col pr-8 ">
          <div className="text-5xl font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-yellow-400 via-purple-500 to-green-400 dark:from-yellow-300 dark:via-purple-400 dark:to-green-300">
            Criston Mascarenhas
          </div>
          <div className="text-sm font-medium pl-1 dark:text-black-200">
            Frontend Developer at{" "}
            <Link
              href="https://timeless.co"
              className="font-bold dark:text-black-200
              hover:text-slate-900 hover:dark:text-black-100 capitalize transition duration-700 ease-in-out"
            >
              Timeless.co
            </Link>
          </div>
          <div className="text-md mt-4 font-semibold italic text-gray-400">
            &quot;Make it work, make it right, make it fast. &quot; - Kent Beck
          </div>
        </div>
        <div className="mb-8 md:ml-auto w-45">
          <Picture
            src="https://avatars.githubusercontent.com/u/20360870?v=4"
            className="inline-block w-full rounded-full"
            alt="crstnmac"
            width="100"
            height="100"
          />
        </div>
      </div>
    </div>
  );
}
